nameOverride: admin-service

image:
  repository: ghcr.io/landersfolk/admin-service
  tag: "latest"   # overwritten by CI on every push to main — see .github/workflows/ci.yml in admin-service
  pullPolicy: Always

containerPort: 7071

service:
  port: 7071

env:
  SPRING_PROFILES_ACTIVE: qa

vault:
  enabled: true
  host: vault-prod
  port: "8200"
  scheme: http
  authMethod: APPROLE
  secretName: admin-service-vault-creds

prometheus:
  enabled: true
  path: /actuator/prometheus
