nameOverride: lander-web

image:
  repository: ghcr.io/landersfolk/lander-web
  tag: "7c7a734"
  pullPolicy: Always

containerPort: 80

service:
  type: LoadBalancer
  port: 80

env: {}

vault:
  enabled: false

prometheus:
  enabled: false
