nameOverride: notification-service

image:
  repository: ghcr.io/landersfolk/notification-service
  tag: "latest"   # overwritten by CI on every push to main — see .github/workflows/ci.yml in notification-service
  pullPolicy: Always

containerPort: 7078

service:
  port: 7078

env:
  SPRING_PROFILES_ACTIVE: qa

vault:
  enabled: true
  host: vault-prod
  port: "8200"
  scheme: http
  authMethod: APPROLE
  secretName: notification-service-vault-creds

prometheus:
  enabled: true
  path: /actuator/prometheus
