apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7077"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: payment-service
        image: localhost:5000/payment-service:qa
        imagePullPolicy: Always
        ports:
        - containerPort: 7077
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "qa"
        - name: VAULT_HOST
          value: "vault-prod"
        - name: VAULT_PORT
          value: "8200"
        - name: VAULT_SCHEME
          value: "http"
        - name: VAULT_AUTH_METHOD
          value: "APPROLE"
        - name: VAULT_ROLE_ID
          valueFrom:
            secretKeyRef:
              name: payment-service-vault-creds
              key: role_id
        - name: VAULT_SECRET_ID
          valueFrom:
            secretKeyRef:
              name: payment-service-vault-creds
              key: secret_id
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - port: 7077
      targetPort: 7077
